In [2]:
import torch

In [17]:
zeros = torch.zeros(3,3)
x1 = zeros.add(3)
x2 = zeros.add(torch.tensor([3,3,3]))
x3 = zeros.add(torch.tensor([[3,3,3],[4,4,4],[5,5,5]]))
x1, x2, x3

(tensor([[3., 3., 3.],
         [3., 3., 3.],
         [3., 3., 3.]]),
 tensor([[3., 3., 3.],
         [3., 3., 3.],
         [3., 3., 3.]]),
 tensor([[3., 3., 3.],
         [4., 4., 4.],
         [5., 5., 5.]]))

In [11]:
import tensorflow as tf

In [18]:
zeros = tf.zeros(3,3)
y1 = tf.add(zeros, 3)
y2 = tf.add(zeros, [3,3,3])
y3 = tf.add(zeros, [[1,1,1], [2,2,2], [3,3,3]])
y1,y2,y3

(<tf.Tensor: shape=(3,), dtype=int32, numpy=array([3, 3, 3])>,
 <tf.Tensor: shape=(3,), dtype=int32, numpy=array([3, 3, 3])>,
 <tf.Tensor: shape=(3, 3), dtype=int32, numpy=
 array([[1, 1, 1],
        [2, 2, 2],
        [3, 3, 3]])>)

## Reduction

In [36]:
x1.sum()

tensor(27.)

## Dot Product