## Vectors in NumPy

In [1]:
import numpy as np

In [9]:
x = np.array([1,2,3,4]) # type argument is optional, e.g. dtype=np.float32
x

array([1, 2, 3, 4])

In [10]:
x.shape

(4,)

In [11]:
x_t = x.T # Transposition a regular 1-D array
x_t

array([1, 2, 3, 4])

In [13]:
x_t.shape

(4,)

In [14]:
z = np.zeros(3) 
z

array([0., 0., 0.])

## Vectors in PyTorch and Tensorflow

In [17]:
import torch
import tensorflow as tf

In [16]:
x_pt = torch.tensor([1,2,3,4])
x_pt

tensor([1, 2, 3, 4])

In [18]:
x_tf = tf.Variable([1,2,3,4])
x_tf

<tf.Variable 'Variable:0' shape=(4,) dtype=int32, numpy=array([1, 2, 3, 4])>