In [1]:
import numpy as np

In [20]:
a = np.array([[1,0,0],[0,1,0],[0,0,1]])
a

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [13]:
for i in range(0,2):
    for j in range(1,3):
        if (i == j):
            continue
        else:
            print("Columns:", a[i], a[j], "\nAnswer:", a[i] * a[j], "\n")

Columns: [1 0 0] [0 1 0] 
Answer: [0 0 0] 

Columns: [1 0 0] [0 0 1] 
Answer: [0 0 0] 

Columns: [0 1 0] [0 0 1] 
Answer: [0 0 0] 



In [27]:
for i in a:
    print("For:", i)
    sum = 0
    for j in i:
        sum += j ** 2
    
    print("Sum: ", sum, "\n\n")

For: [1 0 0]
Sum:  1 


For: [0 1 0]
Sum:  1 


For: [0 0 1]
Sum:  1 




In [32]:
x = np.zeros((10,10))

p = 0
for i in x:
    i[p] = 1
    p += 1


array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [45]:
for i in range(0,9):
    for j in range(i+1,10):
        if i == j:
            continue
        else:
            print(x[i], x[j], "\nOrthogonal dot product:", np.dot(x[i], x[j]))

[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.] [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.] 
Orthogonal dot product: 0.0
[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.] [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.] 
Orthogonal dot product: 0.0
[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.] [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.] 
Orthogonal dot product: 0.0
[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.] [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.] 
Orthogonal dot product: 0.0
[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.] [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.] 
Orthogonal dot product: 0.0
[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.] [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.] 
Orthogonal dot product: 0.0
[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.] [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.] 
Orthogonal dot product: 0.0
[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.] [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.] 
Orthogonal dot product: 0.0
[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.] [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.] 
Orthogonal dot product: 0.0
[0. 1. 0. 0. 0. 0. 0. 0. 0. 0.] [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.] 
Orthogonal dot product: 0.0
[0. 1. 0. 0. 0. 0. 0. 0. 0. 0.] [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.] 
Ortho