In [1]:
import torch

In [47]:
X = torch.tensor([[-1, 2], [3,-2], [5, 7.]])

U, sigma, VT = torch.svd(X)

sigma = torch.linalg.inv(torch.diag(sigma))

In [48]:
t = torch.tensor([[0,0]])

sigma = torch.cat((sigma, t.T), 1)
U, sigma, VT

(tensor([[ 0.1271,  0.4741],
         [ 0.0016, -0.8785],
         [ 0.9919, -0.0593]]),
 tensor([[0.1154, -0.0000, 0.0000],
         [0.0000, 0.2436, 0.0000]]),
 tensor([[ 0.5580, -0.8298],
         [ 0.8298,  0.5580]]))

In [54]:
sigma.shape, U.shape

(torch.Size([2, 3]), torch.Size([3, 2]))

In [44]:
torch.pinverse(X)

tensor([[-0.0877,  0.1777,  0.0758],
        [ 0.0766, -0.1193,  0.0869]])