In [2]:
import numpy as np

In [4]:
A = np.array([[4,2],[-5,-3.]])

evalues, evectors = np.linalg.eig(A)
inv_evectors = np.linalg.inv(evectors)
d = np.diag(evalues)

In [6]:
np.dot(evectors, np.dot(d, inv_evectors))

array([[ 4.,  2.],
       [-5., -3.]])

In [14]:
A = np.array([[2,1],[1,2]])

evalues, evectors = np.linalg.eig(A)
d = np.diag(evalues)

np.dot(evectors, np.dot(d, evectors.T))

array([[2., 1.],
       [1., 2.]])

In [20]:
Q = evectors

Q.dot(Q.T)

array([[1., 0.],
       [0., 1.]])